# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Datatraits Home
email: admin@datatraits.com
description: > # this means to ignore newlines until "baseurl:"
  Datatraits : World is full of Data being produced at X-rate/day(TODO: Provide link). It's a 
  matter of choosing the right combination of 1st/2nd/3rd party data for your business.
  We help provide the best traits for your data and build businesses around them
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://datatraits.com" # the base hostname & protocol for your site
twitter_username: datatraits
github_username:  ccdatatraits

# Build settings
markdown: kramdown
